// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Fetch = require("bs-fetch/src/Fetch.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

((require('isomorphic-fetch')));

var query = "{dogs {\n    name\n    breed\n    description\n  }}";

var payload = { };

payload["query"] = query;

fetch("https://formidadog-ql.now.sh/graphql", Fetch.RequestInit[/* make */0](/* Post */2, {
                  "Content-Type": "application/json"
                }, Caml_option.some(JSON.stringify(payload)), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* () */0)).then((function (prim) {
            return prim.json();
          })).then((function (json) {
          return Promise.resolve((console.log("JSON", json), /* () */0));
        })).catch((function (err) {
        return Promise.resolve((console.log(err), /* () */0));
      }));

exports.query = query;
exports.payload = payload;
/*  Not a pure module */
