// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Axios = require("axios");

var query = "{" + ("dogs {\n    name\n    breed\n    description\n  }" + "}");

Axios.get("https://formidadog-ql.now.sh/graphql?query=" + query).then((function (value) {
          var dogs = value.data;
          console.log("Dogs", value.data);
          return Promise.resolve(dogs);
        })).catch((function (err) {
        console.log("Something went wrong!", err);
        return Promise.resolve(err);
      }));

exports.query = query;
/*  Not a pure module */
