// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var FetchExample$ReactTemplate = require("./FetchExample.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, FetchExample$ReactTemplate.make(/* array */[])), "index");

/*  Not a pure module */
